services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $bundleConfig: '%huh_social_stats%'

  HeimrichHannot\SocialStatsBundle\Command\SocialStatsCommand: ~